services:
  - type: web
    name: blog-platform
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000
